import { DefaultTheme } from "styled-components";

const theme: DefaultTheme = {
  spacing: (value: number) => `${value * 8}px`,
  card: {
    borderRadius: {
      sm: "8px",
      md: "12px",
      lg: "20px",
      helf: "50%",
      full: "100%",
    },
    dropshadow: {
      sm: {
        shadowColor: "#0000001A",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 20,
        elevation: 2,
      },
      md: {
        shadowColor: "#00000026",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
        elevation: 4,
      },
      lg: {
        shadowColor: "#0000001A",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 1,
        shadowRadius: 20,
        elevation: 8,
      },
      fab: {
        shadowColor: "#005ffb",
        shadowOffset: { width: 0, height: 20 },
        shadowOpacity: 0.5,
        shadowRadius: 40,
        elevation: 12,
      },
    },
  },
  typography: {
    body1: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0.15px",
      lineHeight: "24px",
      textTransform: "none",
    },
    body2: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0.2px",
      lineHeight: "20px",
      textTransform: "none",
    },
    body3: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "0.3px",
      lineHeight: "16px",
      textTransform: "none",
    },
    button1: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0.35px",
      lineHeight: "16px",
      textTransform: "none",
    },
    button2: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0.35px",
      lineHeight: "14px",
      textTransform: "none",
    },
    button3: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 500,
      letterSpacing: "0.5px",
      lineHeight: "12px",
      textTransform: "none",
    },

    display1: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "52px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "64px",
      letterSpacing: "0px",
      textTransform: "none",
    },
    display2: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "44px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "52px",
      letterSpacing: "0px",
      textTransform: "none",
    },
    display3: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "36px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "44px",
      letterSpacing: "0px",
      textTransform: "none",
    },

    overline: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 400,
      letterSpacing: "1.5px",
      lineHeight: "12px",
      textTransform: "uppercase",
    },

    label1: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 400,
      lineHeight: "20px",
      letterSpacing: "0.1px",
      textTransform: "none",
    },
    label2: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 400,
      lineHeight: "16px",
      letterSpacing: "0.5px",
      textTransform: "none",
    },
    label3: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "11px",
      fontStyle: "normal",
      fontWeight: 400,
      lineHeight: "16px",
      letterSpacing: "0.5px",
      textTransform: "none",
    },
    label4: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "8px",
      fontStyle: "normal",
      fontWeight: 400,
      lineHeight: "10px",
      letterSpacing: "0px",
      textTransform: "none",
    },

    h1: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "32px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "40px",
      letterSpacing: "0px",
      textTransform: "none",
    },
    h2: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "24px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "32px",
      letterSpacing: "0px",
      textTransform: "none",
    },
    h3: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "20px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "28px",
      letterSpacing: "0px",
      textTransform: "none",
    },
    h4: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "24px",
      letterSpacing: "0.35px",
      textTransform: "none",
    },
    h5: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "20px",
      letterSpacing: "0.1px",
      textTransform: "none",
    },
    h6: {
      fontFamily: `"Poppins", sans-serif`,
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 500,
      lineHeight: "20px",
      letterSpacing: "0.2px",
      textTransform: "none",
    },
  },
  pallete: {
    background: {
      secondary: "#F7F7F7",
      primary: "#FFFFFF",
    },
    colors: {
      primary: {
        yellow: {
          "050": "#FBEDD7",
          "100": "#FEE3B6",
          "200": "#FED38D",
          "300": "#FFC35F",
          "400": "#FAB036",
          "500": "#FAA41F",
          "600": "#E58B14",
          "700": "#C2750F",
          "800": "#AB640D",
          "900": "#844C08",
        },
        magenta: {
          "050": "#FDDFE2",
          "100": "#FBCCD2",
          "200": "#FF9FAC",
          "300": "#FD738B",
          "400": "#F84A69",
          "500": "#EE2252",
          "600": "#DF1445",
          "700": "#C80937",
          "800": "#AA0930",
          "900": "#820825",
        },
        purple: {
          "050": "#F3E9F6",
          "100": "#E9D4EE",
          "200": "#D2A7DD",
          "300": "#BC7CCC",
          "400": "#A550BB",
          "500": "#8E24AA",
          "600": "#76128C",
          "700": "#5C0670",
          "800": "#450554",
          "900": "#350641",
        },
        blue: {
          "050": "#E3EDFF",
          "100": "#D4E4FE",
          "200": "#AAC3ED",
          "300": "#86A7E0",
          "400": "#456EB7",
          "500": "#1B458D",
          "600": "#163771",
          "700": "#102954",
          "800": "#0B1C38",
          "900": "#050E1C",
        },
        ocean: {
          "050": "#E3FBF8",
          "100": "#C9FCFC",
          "200": "#95F2F9",
          "300": "#5FDBEE",
          "400": "#37BCDE",
          "500": "#0092C9",
          "600": "#0071AC",
          "700": "#005590",
          "800": "#003C74",
          "900": "#002B60",
        },
        greenWater: {
          "050": "#D9FFFE",
          "100": "#B7F5F5",
          "200": "#92E8E6",
          "300": "#65D8DC",
          "400": "#3ACDD2",
          "500": "#097685",
          "600": "#0D93A0",
          "700": "#097685",
          "800": "#085B6D",
          "900": "#02404E",
        },
        markGreen: {
          "050": "#D7FFEE",
          "100": "#B7FFE0",
          "200": "#92FFD1",
          "300": "#5FFFBB",
          "400": "#3EFAAB",
          "500": "#1EE591",
          "600": "#08CB79",
          "700": "#01AD65",
          "800": "#007E4A",
          "900": "#04673E",
        },
      },
      secondary: {
        lightBlue: {
          "050": "#E4EEFF",
          "100": "#D1E2FF",
          "200": "#B7D1FF",
          "300": "#99BFFF",
          "400": "#83B0FC",
          "500": "#6B9FF8",
          "600": "#3E75D0",
          "700": "#275CB2",
          "800": "#134699",
          "900": "#072E6C",
        },
        green: {
          "050": "#DFFFE2",
          "100": "#B1F2B8",
          "200": "#84DC8D",
          "300": "#64C96F",
          "400": "#3DAF4A",
          "500": "#32973D",
          "600": "#1C8628",
          "700": "#0F731B",
          "800": "#065E10",
          "900": "#023D09",
        },
      },
      neutral: {
        gray: {
          "050": "#F2F2F2",
          "100": "#E6E6E6",
          "200": "#CCCCCC",
          "300": "#B3B3B3",
          "400": "#999999",
          "500": "#7F7F7F",
          "600": "#666666",
          "700": "#4C4C4C",
          "800": "#333333",
          "900": "#191919",
        },
      },
    },
    button: {
      primary: {
        background: "#005FFB",
        text: "#FAFAFA",
      },
      primaryHover: {
        background: "#3F88FF",
        text: "#FAFAFA",
      },
      primaryActive: {
        background: "#003C9D",
        text: "#FAFAFA",
      },
      secondary: {
        background: "#B2D0FF",
        text: "#00348A",
      },
      secondaryActive: {
        background: "#6193E5",
        text: "#00348A",
      },
      tertiary: {
        background: "transparent",
        text: "#00348A",
      },
      tertiaryActive: {
        background: "#99BFFF",
        text: "#00348A",
      },
      neutral: {
        background: "#E6E6E6",
        text: "#333333",
      },
      neutralActive: {
        background: "#999999",
        text: "#333333",
      },
      neutralTertiary: {
        background: "transparent",
        text: "#333333",
      },
      neutralTertiaryActive: {
        background: "#CCCCCC",
        text: "#191919",
      },
      disabled: {
        background: "#E6E6E6",
        text: "#B3B3B3",
      },
      danger: {
        background: "#EA0F29",
        text: "#FAFAFA",
      },
      dangerHover: {
        background: "#EC5668",
        text: "#FAFAFA",
      },
      dangerActive: {
        background: "#BE071D",
        text: "#FAFAFA",
      },
      dangerTertiary: {
        background: "transparent",
        text: "#EA0F29",
      },
      dangerTertiaryHover: {
        background: "#FFD8DC",
        text: "#EA0F29",
      },
      dangerTertiaryActive: {
        background: "#BE071D",
        text: "#FAFAFA",
      },
      transparent: {
        background: "transparent",
        text: "#191919",
      },
      transparentActive: {
        background: "#FAFAFA33",
        text: "#191919",
      },
      transparentTertiary: {
        background: "transparent",
        text: "#FFFFFF",
      },
      transparentTertiaryActive: {
        background: "#FAFAFA33",
        text: "#FFFFFF",
      },
    },
    typography: {
      primary: "#191919",
      secondary: "#F2F2F2",
      danger: "#9A0013",
      title: "#1E1E1E",
      invert: "#FFFFFF",
    },
    toast: {
      info: {
        text: "#FFFFFF",
        background: "#0046BD",
      },
      success: {
        text: "#191919",
        background: "#6BF88A",
      },
      warning: {
        text: "#191919",
        background: "#FFA924",
      },
      error: {
        text: "#F2F2F2",
        background: "#B40016",
      },
    },
    tags: {
      gray: {
        text: "#191919",
        background: "#F2F2F2",
      },
      ocean: {
        text: "#002B60",
        background: "#C9FCFC",
      },
      red: {
        text: "#820825",
        background: "#FDDFE2",
      },
      yellow: {
        text: "#773805",
        background: "#FEE3B6",
      },
      alternativeYellow: {
        text: "#AB640D",
        background: "#FBF2E4",
      },
      orange: {
        text: "#904B09",
        background: "#FCF3CF",
      },
      blue: {
        text: "#050E1C",
        background: "#CDDEF8",
      },
      alternativeBlue: {
        text: "#203459",
        background: "#D4E4FE",
      },
      purple: {
        text: "#350641",
        background: "#E9D4EE",
      },
      greenWater: {
        text: "#02404E",
        background: "#B7F5F5",
      },
      green: {
        text: "#023D09",
        background: "#D4FFD9",
      },
      teal: {
        text: "#005590",
        background: "#DDFFFB",
      },
      various1: {
        text: "#203459",
        background: "#DBE9FF",
      },
      various2: {
        text: "#003C74",
        background: "#C5FFFF",
      },
    },
  },
};

export default theme;
